/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.concurrency;

public class App {

    public static void main(String[] args) {
        ThreadMap map = new ThreadMap();
        NumberAdder adder = new NumberAdder(map);
        Summarizer summarizer = new Summarizer(map);
        Thread adderThread = new Thread(adder);
        Thread summarizerThread = new Thread(summarizer);
        adderThread.start();
        summarizerThread.start();
    }
}
